name: Memory Lint

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'golem/core/memory/**'
      - 'scripts/memory_lint.py'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'golem/core/memory/**'
      - 'scripts/memory_lint.py'

jobs:
  memory-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        
    - name: Run memory lint with test data
      run: |
        python scripts/memory_lint.py --test --empty-ratio 0.03 --threshold 5.0
      
    - name: Run memory lint with high empty ratio (should warn)
      run: |
        python scripts/memory_lint.py --test --empty-ratio 0.10 --threshold 5.0 || true
        
    - name: Run integration tests
      run: |
        python -m pytest tests/integration/test_collective_memory.py -v